project_id = "exncvylyygvctgwyqpin"

[functions.mercado-pago-checkout]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.get-mp-public-key]
verify_jwt = false

[functions.get-course-price]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.eduzz-webhook]
verify_jwt = false
