project_id = "exncvylyygvctgwyqpin"

[functions.pagseguro-webhook]
verify_jwt = false

[functions.pagseguro-pix-boleto]
verify_jwt = false

[functions.pagseguro-session]
verify_jwt = false

[functions.pagseguro-transparent-checkout]
verify_jwt = false