project_id = "exncvylyygvctgwyqpin"

[functions.pagseguro-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false